
import java.util.HashSet;
import org.jbpm.document.Document;
import com.redhat.demos.bpms_kyc_demo.DocumentsOK;
import com.redhat.demos.bpms_kyc_demo.DocumentsNotOK;
import com.redhat.demos.bpms_kyc_demo.Customer;

//##################### Income Document rules #####################

rule "Clean DocumentsOK income from session."
ruleflow-group "income-documents-check"
salience 100
lock-on-active
when
    $d:DocumentsOK(type == "income")
then
    delete($d);
end 

rule "Reset validation messages on Documents."
ruleflow-group "income-documents-check"
salience 100
lock-on-active
when
    $d:Document()
then
    $d.addAttribute("validationMessage", null);
end 


rule "Passport Document Check - Document starts with surname of customer"
ruleflow-group "income-documents-check"
when
    Customer($s:surname)
    $d:Document(name not str[startsWith] $s)
then
    System.out.println("Passport not OK. Does not start with name of customer");
    insertLogical(new DocumentsNotOK($d.getIdentifier(), "passport", "Passport filename does not start with name of customer."));    
end

/*
rule "Initialize validation message attribute"
when
    $d: Document(getAttribute("validationMessages") == null)
then
    $d.addAttribute("validationMessages", new HashSet());
end
*/

/*
rule "Set Validation Messages on document"
when
    $d: Document(getAttributes("validationMessages") != null)
    DocumentsNotOK(type == "passport", $m: message)
then
    $d.getAttribute("validationMessages").add($m);
end
*/


//Run this rule last. Only if there are no DocumentNotOK facts for all our type will we say that our Income Documents are OK.
//We can't user insertLogical here, because the RFG node will retract the facts from WM when it's finished.
//This means that all matches are removed and thus the "DocumentsOK("incomce"))" fact will be removed from WM
// as well. This causes the gateway not to work because the gateway checks the presence of a fact in WM.
rule "AllIncomeDocumentsOK"
ruleflow-group "income-documents-check"
salience -100
when
    not(DocumentsNotOK(type == "passport"))
then
    System.out.println("All income documents OK.");
    insert(new DocumentsOK("income"));
end


//##################### Milestone Document rules #####################

rule "Documents OK"
ruleflow-group "documents-check"
when
    DocumentsOK(type == "income")
then
    System.out.println("Documents OK");
    insert (new DocumentsOK("kyc"));
end
    
