
import org.jbpm.document.Document;
import com.redhat.demos.bpms_kyc_demo.DocumentsOK;
import com.redhat.demos.bpms_kyc_demo.Customer;

//##################### Income Document rules #####################

//The Passport document is valid when the document name equals the name surname of the Customer

rule "Debug Passport Document Check"
ruleflow-group "income-documents-check"
when
    Customer($s:surname)
    $d:Document()
then
    System.out.println("Customer surname: " + $s);
    System.out.println("Document name: " + $d.getName());
end



rule "Passport Document Check"
ruleflow-group "income-documents-check"
when
    Customer($s:surname)
    $d:Document(name str[startsWith] $s)
then
    System.out.println("Passport OK");
    insertLogical(new DocumentsOK("passport"));
end


rule "AllIncomeDocumentsOK"
ruleflow-group "income-documents-check"
when
    DocumentsOK(type == "passport")
then
    insertLogical(new DocumentsOK("income"));
end


rule "Documents OK"
ruleflow-group "documents-check"
when
    DocumentsOK(type == "income")
then
    System.out.println("Documents OK");
    insert (new DocumentsOK("kyc"));
end
    
