package com.redhat.demos.bpms_kyc_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   private java.lang.String id;

   public Application()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public Application(java.lang.String id)
   {
      this.id = id;
   }

}