package com.redhat.demos.bpms_kyc_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "ID")
   private java.lang.String id;
   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Surname")
   private java.lang.String surname;
   @org.kie.api.definition.type.Label(value = "Social Security Number")
   private java.lang.String ssn;
   @org.kie.api.definition.type.Label(value = "E-mail Address")
   private java.lang.String email;

   public Customer()
   {
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getSurname()
   {
      return this.surname;
   }

   public void setSurname(java.lang.String surname)
   {
      this.surname = surname;
   }

   public java.lang.String getSsn()
   {
      return this.ssn;
   }

   public void setSsn(java.lang.String ssn)
   {
      this.ssn = ssn;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public Customer(java.lang.String id, java.lang.String name,
         java.lang.String surname, java.lang.String ssn,
         java.lang.String email)
   {
      this.id = id;
      this.name = name;
      this.surname = surname;
      this.ssn = ssn;
      this.email = email;
   }

}