package com.redhat.demos.bpms_kyc_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentCheckResponse implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Documents OK")
   private boolean documentsOk;

   public DocumentCheckResponse()
   {
   }

   public boolean isDocumentsOk()
   {
      return this.documentsOk;
   }

   public void setDocumentsOk(boolean documentsOk)
   {
      this.documentsOk = documentsOk;
   }

   public DocumentCheckResponse(boolean documentsOk)
   {
      this.documentsOk = documentsOk;
   }

}