package com.redhat.demos.bpms_kyc_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentsOK implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Docuement Type")
   private java.lang.String documentType;

   public DocumentsOK()
   {
   }

   public java.lang.String getDocumentType()
   {
      return this.documentType;
   }

   public void setDocumentType(java.lang.String documentType)
   {
      this.documentType = documentType;
   }

   public DocumentsOK(java.lang.String documentType)
   {
      this.documentType = documentType;
   }

}