package com.redhat.demos.bpms_kyc_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentsOK implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DocumentsOK() {
    }

}