package com.redhat.demos.bpms_kyc_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentsCheckResponse implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Documents OK")
   private boolean documentsOk;

   @org.kie.api.definition.type.Label(value = "Type")
   private java.lang.String type;

   public DocumentsCheckResponse()
   {
   }

   public boolean isDocumentsOk()
   {
      return this.documentsOk;
   }

   public void setDocumentsOk(boolean documentsOk)
   {
      this.documentsOk = documentsOk;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public DocumentsCheckResponse(boolean documentsOk, java.lang.String type)
   {
      this.documentsOk = documentsOk;
      this.type = type;
   }

}