package com.redhat.demos.bpms_kyc_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DocumentsNotOK implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Document Type")
   private java.lang.String type;

   @org.kie.api.definition.type.Label("Message")
   private java.lang.String message;

   @org.kie.api.definition.type.Label(value = "Document ID")
   private java.lang.String documentId;

   public DocumentsNotOK()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getMessage()
   {
      return this.message;
   }

   public void setMessage(java.lang.String message)
   {
      this.message = message;
   }

   public java.lang.String getDocumentId()
   {
      return this.documentId;
   }

   public void setDocumentId(java.lang.String documentId)
   {
      this.documentId = documentId;
   }

   public DocumentsNotOK(java.lang.String type, java.lang.String message,
         java.lang.String documentId)
   {
      this.type = type;
      this.message = message;
      this.documentId = documentId;
   }

}